// LOCALHOST
###
GET http://localhost:3000/
###
GET http://localhost:3000/contacts

###
GET http://localhost:3000/contacts/1

###
GET http://localhost:3000/contacts/2

###
GET http://localhost:3000/contacts/3

// PRODUCTION
###
GET https://project-1-ux8i.onrender.com/
###
GET https://project-1-ux8i.onrender.com/contacts

###
GET https://project-1-ux8i.onrender.com/contacts/1

###
GET https://project-1-ux8i.onrender.com/contacts/2

###
GET https://project-1-ux8i.onrender.com/contacts/3